# Generated by Django 3.2.3 on 2021-06-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210612_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='E2Jy8-QUUAYyJxe.jpg', null=True, upload_to=''),
        ),
    ]
