# Generated by Django 3.2.3 on 2021-06-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
