# Generated by Django 3.2.3 on 2021-06-13 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_abonnement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='abonnmentChoisit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.abonnement'),
        ),
    ]
