# Generated by Django 3.2.3 on 2021-06-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210613_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='abonnmentChoisit',
        ),
        migrations.AddField(
            model_name='customer',
            name='abonnmentChoisit',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='accounts.Abonnement'),
        ),
    ]
