# Generated by Django 3.2.3 on 2021-06-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_order_abonne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='abonnmentChoisit',
        ),
        migrations.AddField(
            model_name='customer',
            name='abo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.order'),
        ),
    ]
