# Generated by Django 3.2.3 on 2021-06-16 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_auto_20210616_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='abonne',
            field=models.ForeignKey(default='nom', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
