# Generated by Django 3.2.3 on 2021-06-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
